name: endgame
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.8
  local_auth: ^1.1.8
  pie_chart: ^5.3.0
  animated_bottom_navigation_bar: ^0.3.3
  auto_size_text: ^3.0.0
  circular_reveal_animation: ^2.0.1
  charts_flutter: ^0.12.0
  get: ^4.6.5
  money_converter: ^0.0.4
  currency_text_input_formatter: ^2.1.5
  cupertino_icons: ^1.0.2
  fl_chart: ^0.40.2
  intl: ^0.17.0
  flutter_inappwebview: ^5.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/expense.png
    - assets/icon.png
    - assets/face.png
    - assets/money_1.png

  fonts:
    - family: customFont
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-Regular.ttf
        - asset: assets/fonts/DM_Sans/DMSans-Medium.ttf
          weight: 600
        - asset: assets/fonts/DM_Sans/DMSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/DM_Sans/DMSans-Bold.ttf
          weight: 900
